export enum EErrorUpload {
	FOLDER_NOT_FOUND = "FOLDER_NOT_FOUND",
	FOLDER_NOT_EXIST = "FOLDER_NOT_EXIST",
	FOLDER_EXISTED = "FOLDER_EXISTED",

	IMAGE_NOT_FOUND = "IMAGE_NOT_FOUND",
	IMAGE_NOT_EXIST = "IMAGE_NOT_EXIST",

}