name: Bug Report
description: File a bug report
title: '[BUG]: '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you do? What happened? What did you expect to happen?
      placeholder: Put your description of the bug here.
    validations:
      required: true
